removed control directory - no longer needed
NorESMhub/CAM-Nor-physics pull request #10
Opened 2024-02-24 10:38 UTC by mvertens

Summary: removal of control directory - it is no longer needed.

Contributors: mvertens

Reviewers: @gold2718 

Purpose of changes: Minimize number of files in camnor_physics and remove duplicate files where possible

Changes made to build system: None

Changes made to the namelist: None

Changes to the defaults for the boundary datasets: None

Substantial timing or memory changes: None

Ran aux_cam_noresm and compared to baseline noresm_v9_cam6_3_123

2024-02-28 20:10 UTC, mvertens commented
@gold2718 - could you please review this - I need it to be consistent with the latest changes I am making to the use_cases and rewrite of the oslo_aero prescribed_volcaero.

2024-02-29 10:20 UTC, gold2718 requested changes
One simple change needed.

2024-02-29 10:20 UTC, gold2718 commented on physics/physpkg.F90
> +    logical   :: first_call = .true.
This is not used, please remove.

2024-02-29 10:30 UTC, mvertens commented on physics/physpkg.F90
> +    logical   :: first_call = .true.
Done.

2024-02-29 11:43 UTC, mvertens commented
@gold2718 - can you please merge this - or should I?

2024-02-29 13:54 UTC, gold2718 commented
> gold2718 - can you please merge this - or should I?

Merge is done by the assignee, _after_ it is approved.

2024-02-29 13:58 UTC, gold2718 approved these changes
Looks good now.

2024-02-29 14:00 UTC, merged